version: "3"
services:
  web:
    container_name: web
    image: bibliospringurjc
    ports:
      - 8444:8444
    links:
      - db
      - sv
    depends_on:
      - db
      - sv
    volumes:
      - /data/BiblioSpring
    networks:
      movie-quote-network:
        aliases:
          - web 
    restart: always
    environment:
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/bibliospringdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  db:
    container_name: db
    image: mysql:5.7
    networks:
      movie-quote-network:
        aliases:
          - db
    restart: always
    volumes:
        - /data/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=bibliospringdb
      - MYSQL_ONETIME_PASSWORD=true
  sv:
    container_name: sv
    image: servicio_interno
    ports: 
      - 8071:8071
    restart: always
    volumes:
      - /data/sevicioInterno
    networks:
      movie-quote-network:
        aliases:
          - sv
networks:
    movie-quote-network:

  
