version: "3"

services:
  web:
  ##con create jar
    container_name: web
    image: web
    #ports:
    #  - "8080:8080"
    networks:
      movie-quote-network:
        aliases:
          - web 
    restart: unless-stopped
    environment:
      - SPRING.DATASOURCE.USERNAME=root
      - SPRING.DATASOURCE.PASSWORD=123456
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/bibliospringdb
    links:
      - db
      - sv 
  web1:
  ##sin create solo none
    container_name: web1
    image: web1
    #ports:
    #  - "8081:8080"
    networks:
      movie-quote-network:
        aliases:
          - web1 
    restart: unless-stopped
    environment:
      - SPRING.DATASOURCE.USERNAME=root
      - SPRING.DATASOURCE.PASSWORD=123456
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/bibliospringdb
    links:
      - db
      - web
      - sv
  db:
    container_name: db
    image: mysql:5.7
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=bibliospringdb
      - MYSQL_ONETIME_PASSWORD=true
    networks:
      movie-quote-network:
        aliases:
          - db
    restart: unless-stopped
  sv:
    container_name: sv
    image: servicio_interno
    ports:
      - "8071:8071"
    restart: unless-stopped
    networks:
      movie-quote-network:
        aliases:
          - sv
  lb:
    build: 
      context: ./haProxy
    container_name: haProxy_lb
    image: balancer
    ports:
      # Only service that is exposed to the host is the lb 
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      movie-quote-network:
        aliases:
          - lb 
    links:
      - web
      - web1
networks:
  movie-quote-network: