version: "3"

services:
##base de datos
  db:
    container_name: db
    image: mysql:5.7
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=bibliospringdb
      - MYSQL_ONETIME_PASSWORD=true
    networks:
      movie-quote-network:
        aliases:
          - db
    restart: unless-stopped
  web:
  ##con create jar
    container_name: web
    image: web
    #ports:
    #  - "8080:8080"
    networks:
      movie-quote-network:
        aliases:
          - web 
    restart: unless-stopped
    environment:
      - SPRING.DATASOURCE.USERNAME=root
      - SPRING.DATASOURCE.PASSWORD=123456
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/bibliospringdb
    links:
      - db
      - sv
  web1:
  ##sin create solo none
    container_name: web1
    image: web1
    #ports:
    #  - "8081:8080"
    networks:
      movie-quote-network:
        aliases:
          - web1 
    restart: unless-stopped
    environment:
      - SPRING.DATASOURCE.USERNAME=root
      - SPRING.DATASOURCE.PASSWORD=123456
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/bibliospringdb
    links:
      - db
      - sv
  ##balanceador WEB
  lb:
    build: 
      context: ./haProxy
    container_name: haProxy_lb
    image: balancer_web
    ports:
      # Only service that is exposed to the host is the lb 
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      movie-quote-network:
        aliases:
          - lb 
    links:
      - web
      - web1  
  sv1:
    container_name: sv1
    image: sv1
    #ports:
    #  - "8071:8071"
    restart: unless-stopped
    networks:
      movie-quote-network:
        aliases:
          - sv1
  sv2:
    container_name: sv2
    image: sv2
    #ports:
    #  - "8071:8071"
    restart: unless-stopped
    networks:
      movie-quote-network:
        aliases:
          - sv2
  ##Balanceador SI
  sv:
    build: 
      context: ./haProxySI
    container_name: haProxy_SI
    image: balancer_sv
    ports:
      # Only service that is exposed to the host is the lb 
      - "8071:8071"
    restart: unless-stopped
    networks:
      movie-quote-network:
        aliases:
          - sv 
    links:
      - sv1
      - sv2
networks:
  movie-quote-network: